// lib/storage/localProvider.js
// The LocalStorageProvider — file bytes on this server's own disk. All fs access
// lives here; API handlers never touch fs directly, so a future S3/R2/Synology
// provider is a drop-in.
//
// Layout (STORAGE_ROOT points at the data dir; tmp/ and trash/ are siblings):
//   <DATA_DIR>\<projectId>\objects\<YYYY>\<MM>\<objId>     committed objects
//   <TMP_DIR>\<objId>.part                                  in-flight uploads
//   <TRASH_DIR>\<projectId>\objects\<YYYY>\<MM>\<objId>     trashed objects
//
// A `storageKey` is the object's path RELATIVE to DATA_DIR (e.g.
// "<projectId>/objects/2026/09/<objId>"). It is generated by this module from
// random bytes + the date — never from a user-supplied filename — and is kept
// server-side only (never returned by the API).

import fs from "fs";
import path from "path";
import crypto from "crypto";
import config from "@/lib/config";

const DATA_DIR = path.resolve(config.storageRoot);
const BASE_DIR = path.dirname(DATA_DIR);
const TMP_DIR = path.join(BASE_DIR, "tmp");
const TRASH_DIR = path.join(BASE_DIR, "trash");
// Chunked-upload temp files live in their OWN subdirectory: cleanTempFiles()
// only scans tmp/*.part at the top level, so a paused-but-resumable chunked
// upload can never be swept by the plain mtime cleaner. Same volume as DATA_DIR,
// so the final commit is still an atomic rename.
const CHUNK_DIR = path.join(TMP_DIR, "chunked");

export const name = "local";
export const dirs = { DATA_DIR, BASE_DIR, TMP_DIR, TRASH_DIR, CHUNK_DIR }; // internal only

export async function ensureStorage() {
  await fs.promises.mkdir(DATA_DIR, { recursive: true });
  await fs.promises.mkdir(TMP_DIR, { recursive: true });
  await fs.promises.mkdir(TRASH_DIR, { recursive: true });
}

export async function checkStorageAccess() {
  try {
    await fs.promises.mkdir(DATA_DIR, { recursive: true });
    const probe = path.join(DATA_DIR, `.probe-${process.pid}-${Date.now()}`);
    await fs.promises.writeFile(probe, "ok");
    await fs.promises.unlink(probe);
    return { ok: true };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

// Defense-in-depth: a storageKey must resolve to a path INSIDE the given root.
// storageKeys are server-generated, but this guarantees no "../" can ever
// escape, whatever a future caller passes.
function safeResolve(root, storageKey) {
  const full = path.resolve(root, storageKey);
  const rel = path.relative(root, full);
  if (rel.startsWith("..") || path.isAbsolute(rel)) {
    throw Object.assign(new Error("Invalid storage key."), { code: "INVALID_STORAGE_KEY" });
  }
  return full;
}

/**
 * Begin a streamed write into tmp/. Returns a handle the caller pipes into and
 * later commits or aborts. The physical path stays inside the handle.
 */
export function beginWrite() {
  fs.mkdirSync(TMP_DIR, { recursive: true });
  const objId = crypto.randomBytes(16).toString("hex");
  const tmpPath = path.join(TMP_DIR, `${objId}.part`);
  const stream = fs.createWriteStream(tmpPath);
  return { objId, tmpPath, stream };
}

/**
 * Promote a finished tmp file to its committed object location and stat it.
 * The storageKey is built here from projectId + date + objId.
 */
export async function commit(handle, { projectId }) {
  const now = new Date();
  const yyyy = String(now.getUTCFullYear());
  const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
  const storageKey = path.posix.join(String(projectId), "objects", yyyy, mm, handle.objId);
  const finalPath = safeResolve(DATA_DIR, storageKey);
  await fs.promises.mkdir(path.dirname(finalPath), { recursive: true });
  await fs.promises.rename(handle.tmpPath, finalPath);
  const st = await fs.promises.stat(finalPath);
  return { storageKey, bytes: st.size };
}

/** Discard an in-flight write. Best-effort. */
export async function abort(handle) {
  try {
    handle.stream.destroy();
  } catch {
    /* already closed */
  }
  try {
    await fs.promises.unlink(handle.tmpPath);
  } catch {
    /* nothing to remove */
  }
}

/**
 * A read stream for a committed object, optionally ranged. fs.createReadStream
 * with {start,end} SEEKS — it never reads the bytes before `start` — which is
 * what makes Range requests cheap on large files. Returns null if missing.
 */
export function openRead(storageKey, { start, end } = {}) {
  const full = safeResolve(DATA_DIR, storageKey);
  if (!fs.existsSync(full)) return null;
  const opts = {};
  if (typeof start === "number") opts.start = start;
  if (typeof end === "number") opts.end = end; // inclusive
  return fs.createReadStream(full, opts);
}

export async function stat(storageKey) {
  try {
    const s = await fs.promises.stat(safeResolve(DATA_DIR, storageKey));
    return { bytes: s.size };
  } catch {
    return null;
  }
}

export async function exists(storageKey) {
  return (await stat(storageKey)) !== null;
}

/** Move a committed object into trash/ (a rename — instant on the same volume). */
export async function moveToTrash(storageKey) {
  const from = safeResolve(DATA_DIR, storageKey);
  const to = safeResolve(TRASH_DIR, storageKey);
  await fs.promises.mkdir(path.dirname(to), { recursive: true });
  try {
    await fs.promises.rename(from, to);
    return true;
  } catch (e) {
    if (e.code === "ENOENT") return false; // physical already gone (orphan)
    throw e;
  }
}

/** Permanently delete a committed object. Best-effort (missing = success). */
export async function remove(storageKey) {
  try {
    await fs.promises.unlink(safeResolve(DATA_DIR, storageKey));
    return true;
  } catch (e) {
    if (e.code === "ENOENT") return true;
    throw e;
  }
}

/** Move a trashed object back to active storage (restore). */
export async function restoreFromTrash(storageKey) {
  const from = safeResolve(TRASH_DIR, storageKey);
  const to = safeResolve(DATA_DIR, storageKey);
  await fs.promises.mkdir(path.dirname(to), { recursive: true });
  try {
    await fs.promises.rename(from, to);
    return true;
  } catch (e) {
    if (e.code === "ENOENT") return false;
    throw e;
  }
}

/** Permanently delete a trashed object's bytes. */
export async function removeFromTrash(storageKey) {
  try {
    await fs.promises.unlink(safeResolve(TRASH_DIR, storageKey));
    return true;
  } catch (e) {
    if (e.code === "ENOENT") return true;
    throw e;
  }
}

export async function statTrash(storageKey) {
  try {
    const s = await fs.promises.stat(safeResolve(TRASH_DIR, storageKey));
    return { bytes: s.size };
  } catch {
    return null;
  }
}

/** Streaming SHA-256 of a committed (active) object — for the integrity full check. */
export function sha256Of(storageKey) {
  return new Promise((resolve, reject) => {
    const h = crypto.createHash("sha256");
    const s = fs.createReadStream(safeResolve(DATA_DIR, storageKey));
    s.on("data", (c) => h.update(c));
    s.on("end", () => resolve(h.digest("hex")));
    s.on("error", reject);
  });
}

/** Every object file under a root (data or trash), as relative storageKeys. */
async function walk(root) {
  const out = [];
  async function rec(dir) {
    let ents;
    try {
      ents = await fs.promises.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of ents) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) await rec(full);
      else {
        if (e.name.startsWith(".probe") || e.name.endsWith(".part")) continue;
        out.push(path.relative(root, full).split(path.sep).join("/"));
      }
    }
  }
  await rec(root);
  return out;
}
export const listDataObjects = () => walk(DATA_DIR);
export const listTrashObjects = () => walk(TRASH_DIR);

// ── Chunked-upload temp files (tmp/chunked/<objId>.part) ─────────────────────
// The objId is server-generated (32 hex) and validated on every use, so no
// caller-supplied value can ever become part of a path.
const CHUNK_OBJ_RE = /^[a-f0-9]{32}$/;
function chunkTempPath(objId) {
  if (!CHUNK_OBJ_RE.test(String(objId))) {
    throw Object.assign(new Error("Invalid temp object id."), { code: "INVALID_STORAGE_KEY" });
  }
  return path.join(CHUNK_DIR, `${objId}.part`);
}

/** Create an empty temp file for a new chunked upload. Returns { objId }. */
export async function createChunkTemp() {
  await fs.promises.mkdir(CHUNK_DIR, { recursive: true });
  const objId = crypto.randomBytes(16).toString("hex");
  const fh = await fs.promises.open(chunkTempPath(objId), "wx"); // exclusive create
  await fh.close();
  return { objId };
}

/** A handle compatible with commit()/abort(), for the final atomic promote. */
export function chunkTempHandle(objId) {
  return { objId, tmpPath: chunkTempPath(objId) };
}

export async function statChunkTemp(objId) {
  try {
    const s = await fs.promises.stat(chunkTempPath(objId));
    return { bytes: s.size, mtimeMs: s.mtimeMs };
  } catch {
    return null;
  }
}

/** Cut the temp back to `size` — discards a partial/failed chunk before a retry. */
export async function truncateChunkTemp(objId, size) {
  await fs.promises.truncate(chunkTempPath(objId), size);
}

/** Write stream positioned at `offset` (r+ never truncates what came before). */
export function openChunkWrite(objId, offset) {
  return fs.createWriteStream(chunkTempPath(objId), { flags: "r+", start: offset });
}

/** Flush the temp file's data to the device before a chunk is acknowledged. */
export async function syncChunkTemp(objId) {
  const fh = await fs.promises.open(chunkTempPath(objId), "r+");
  try {
    await fh.datasync();
  } finally {
    await fh.close();
  }
}

export function openChunkRead(objId, { highWaterMark } = {}) {
  return fs.createReadStream(chunkTempPath(objId), highWaterMark ? { highWaterMark } : {});
}

/** Delete a temp file. Missing = success. */
export async function removeChunkTemp(objId) {
  try {
    await fs.promises.unlink(chunkTempPath(objId));
    return true;
  } catch (e) {
    if (e.code === "ENOENT") return true;
    throw e;
  }
}

/** Every chunk temp file with its size and mtime (for the orphan reaper). */
export async function listChunkTemps() {
  let names = [];
  try {
    names = await fs.promises.readdir(CHUNK_DIR);
  } catch {
    return [];
  }
  const out = [];
  for (const name of names) {
    const m = /^([a-f0-9]{32})\.part$/.exec(name);
    if (!m) continue;
    try {
      const s = await fs.promises.stat(path.join(CHUNK_DIR, name));
      out.push({ objId: m[1], bytes: s.size, mtimeMs: s.mtimeMs });
    } catch {
      /* vanished */
    }
  }
  return out;
}

// ── Whole-project teardown (permanent project deletion) ──────────────────────
// Every object of a project lives under <DATA_DIR>\<projectId>\ or
// <TRASH_DIR>\<projectId>\ — commit() builds each storageKey from the project
// id. The id is validated as a MongoDB ObjectId (24 hex) and resolved through
// safeResolve, so nothing a user typed can become part of these paths.
const PROJECT_ID_RE = /^[a-f0-9]{24}$/;
function projectDirs(projectId) {
  const id = String(projectId);
  if (!PROJECT_ID_RE.test(id)) {
    throw Object.assign(new Error("Invalid project id."), { code: "INVALID_STORAGE_KEY" });
  }
  return { data: safeResolve(DATA_DIR, id), trash: safeResolve(TRASH_DIR, id) };
}

async function treeUsage(dir) {
  const out = { files: 0, bytes: 0 };
  async function rec(d) {
    let ents;
    try {
      ents = await fs.promises.readdir(d, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of ents) {
      const full = path.join(d, e.name);
      if (e.isDirectory()) await rec(full);
      else {
        out.files++;
        try {
          out.bytes += (await fs.promises.lstat(full)).size;
        } catch {
          /* vanished */
        }
      }
    }
  }
  await rec(dir);
  return out;
}

async function present(p) {
  try {
    await fs.promises.lstat(p);
    return true;
  } catch (e) {
    return e.code !== "ENOENT"; // anything but "not there" counts as still there
  }
}

/** What is physically on disk for a project, in data/ and trash/. */
export async function projectStorageUsage(projectId) {
  const dirs = projectDirs(projectId);
  return {
    data: await treeUsage(dirs.data),
    trash: await treeUsage(dirs.trash),
    exists: (await present(dirs.data)) || (await present(dirs.trash)),
  };
}

/**
 * Remove a project's data and trash directories with everything still in them
 * (objects no record points at, empty year/month folders). Returns what was
 * there. Throws if either directory is still present afterwards (e.g. a file
 * held open on Windows) — the caller reports the stage as failed.
 */
export async function removeProjectStorage(projectId) {
  const dirs = projectDirs(projectId);
  const found = { data: await treeUsage(dirs.data), trash: await treeUsage(dirs.trash) };
  for (const dir of [dirs.data, dirs.trash]) {
    await fs.promises.rm(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
    if (await present(dir)) throw Object.assign(new Error("Project storage directory is still present."), { code: "EBUSY" });
  }
  return found;
}

export default {
  name,
  dirs,
  projectStorageUsage,
  removeProjectStorage,
  ensureStorage,
  checkStorageAccess,
  beginWrite,
  commit,
  abort,
  openRead,
  stat,
  exists,
  moveToTrash,
  remove,
  restoreFromTrash,
  removeFromTrash,
  statTrash,
  sha256Of,
  listDataObjects,
  listTrashObjects,
  createChunkTemp,
  chunkTempHandle,
  statChunkTemp,
  truncateChunkTemp,
  openChunkWrite,
  syncChunkTemp,
  openChunkRead,
  removeChunkTemp,
  listChunkTemps,
};
