// lib/storage/localProvider.js
// The LocalStorageProvider — file bytes on this server's own disk. All fs access
// lives here; API handlers never touch fs directly, so a future S3/R2/Synology
// provider is a drop-in.
//
// Layout (STORAGE_ROOT points at the data dir; tmp/ and trash/ are siblings):
//   <DATA_DIR>\<projectId>\objects\<YYYY>\<MM>\<objId>     committed objects
//   <TMP_DIR>\<objId>.part                                  in-flight uploads
//   <TRASH_DIR>\<projectId>\objects\<YYYY>\<MM>\<objId>     trashed objects
//
// A `storageKey` is the object's path RELATIVE to DATA_DIR (e.g.
// "<projectId>/objects/2026/09/<objId>"). It is generated by this module from
// random bytes + the date — never from a user-supplied filename — and is kept
// server-side only (never returned by the API).

import fs from "fs";
import path from "path";
import crypto from "crypto";
import config from "@/lib/config";

const DATA_DIR = path.resolve(config.storageRoot);
const BASE_DIR = path.dirname(DATA_DIR);
const TMP_DIR = path.join(BASE_DIR, "tmp");
const TRASH_DIR = path.join(BASE_DIR, "trash");

export const name = "local";
export const dirs = { DATA_DIR, BASE_DIR, TMP_DIR, TRASH_DIR }; // internal only

export async function ensureStorage() {
  await fs.promises.mkdir(DATA_DIR, { recursive: true });
  await fs.promises.mkdir(TMP_DIR, { recursive: true });
  await fs.promises.mkdir(TRASH_DIR, { recursive: true });
}

export async function checkStorageAccess() {
  try {
    await fs.promises.mkdir(DATA_DIR, { recursive: true });
    const probe = path.join(DATA_DIR, `.probe-${process.pid}-${Date.now()}`);
    await fs.promises.writeFile(probe, "ok");
    await fs.promises.unlink(probe);
    return { ok: true };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

// Defense-in-depth: a storageKey must resolve to a path INSIDE the given root.
// storageKeys are server-generated, but this guarantees no "../" can ever
// escape, whatever a future caller passes.
function safeResolve(root, storageKey) {
  const full = path.resolve(root, storageKey);
  const rel = path.relative(root, full);
  if (rel.startsWith("..") || path.isAbsolute(rel)) {
    throw Object.assign(new Error("Invalid storage key."), { code: "INVALID_STORAGE_KEY" });
  }
  return full;
}

/**
 * Begin a streamed write into tmp/. Returns a handle the caller pipes into and
 * later commits or aborts. The physical path stays inside the handle.
 */
export function beginWrite() {
  fs.mkdirSync(TMP_DIR, { recursive: true });
  const objId = crypto.randomBytes(16).toString("hex");
  const tmpPath = path.join(TMP_DIR, `${objId}.part`);
  const stream = fs.createWriteStream(tmpPath);
  return { objId, tmpPath, stream };
}

/**
 * Promote a finished tmp file to its committed object location and stat it.
 * The storageKey is built here from projectId + date + objId.
 */
export async function commit(handle, { projectId }) {
  const now = new Date();
  const yyyy = String(now.getUTCFullYear());
  const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
  const storageKey = path.posix.join(String(projectId), "objects", yyyy, mm, handle.objId);
  const finalPath = safeResolve(DATA_DIR, storageKey);
  await fs.promises.mkdir(path.dirname(finalPath), { recursive: true });
  await fs.promises.rename(handle.tmpPath, finalPath);
  const st = await fs.promises.stat(finalPath);
  return { storageKey, bytes: st.size };
}

/** Discard an in-flight write. Best-effort. */
export async function abort(handle) {
  try {
    handle.stream.destroy();
  } catch {
    /* already closed */
  }
  try {
    await fs.promises.unlink(handle.tmpPath);
  } catch {
    /* nothing to remove */
  }
}

/**
 * A read stream for a committed object, optionally ranged. fs.createReadStream
 * with {start,end} SEEKS — it never reads the bytes before `start` — which is
 * what makes Range requests cheap on large files. Returns null if missing.
 */
export function openRead(storageKey, { start, end } = {}) {
  const full = safeResolve(DATA_DIR, storageKey);
  if (!fs.existsSync(full)) return null;
  const opts = {};
  if (typeof start === "number") opts.start = start;
  if (typeof end === "number") opts.end = end; // inclusive
  return fs.createReadStream(full, opts);
}

export async function stat(storageKey) {
  try {
    const s = await fs.promises.stat(safeResolve(DATA_DIR, storageKey));
    return { bytes: s.size };
  } catch {
    return null;
  }
}

export async function exists(storageKey) {
  return (await stat(storageKey)) !== null;
}

/** Move a committed object into trash/ (a rename — instant on the same volume). */
export async function moveToTrash(storageKey) {
  const from = safeResolve(DATA_DIR, storageKey);
  const to = safeResolve(TRASH_DIR, storageKey);
  await fs.promises.mkdir(path.dirname(to), { recursive: true });
  try {
    await fs.promises.rename(from, to);
    return true;
  } catch (e) {
    if (e.code === "ENOENT") return false; // physical already gone (orphan)
    throw e;
  }
}

/** Permanently delete a committed object. Best-effort (missing = success). */
export async function remove(storageKey) {
  try {
    await fs.promises.unlink(safeResolve(DATA_DIR, storageKey));
    return true;
  } catch (e) {
    if (e.code === "ENOENT") return true;
    throw e;
  }
}

/** Move a trashed object back to active storage (restore). */
export async function restoreFromTrash(storageKey) {
  const from = safeResolve(TRASH_DIR, storageKey);
  const to = safeResolve(DATA_DIR, storageKey);
  await fs.promises.mkdir(path.dirname(to), { recursive: true });
  try {
    await fs.promises.rename(from, to);
    return true;
  } catch (e) {
    if (e.code === "ENOENT") return false;
    throw e;
  }
}

/** Permanently delete a trashed object's bytes. */
export async function removeFromTrash(storageKey) {
  try {
    await fs.promises.unlink(safeResolve(TRASH_DIR, storageKey));
    return true;
  } catch (e) {
    if (e.code === "ENOENT") return true;
    throw e;
  }
}

export async function statTrash(storageKey) {
  try {
    const s = await fs.promises.stat(safeResolve(TRASH_DIR, storageKey));
    return { bytes: s.size };
  } catch {
    return null;
  }
}

/** Streaming SHA-256 of a committed (active) object — for the integrity full check. */
export function sha256Of(storageKey) {
  return new Promise((resolve, reject) => {
    const h = crypto.createHash("sha256");
    const s = fs.createReadStream(safeResolve(DATA_DIR, storageKey));
    s.on("data", (c) => h.update(c));
    s.on("end", () => resolve(h.digest("hex")));
    s.on("error", reject);
  });
}

/** Every object file under a root (data or trash), as relative storageKeys. */
async function walk(root) {
  const out = [];
  async function rec(dir) {
    let ents;
    try {
      ents = await fs.promises.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of ents) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) await rec(full);
      else {
        if (e.name.startsWith(".probe") || e.name.endsWith(".part")) continue;
        out.push(path.relative(root, full).split(path.sep).join("/"));
      }
    }
  }
  await rec(root);
  return out;
}
export const listDataObjects = () => walk(DATA_DIR);
export const listTrashObjects = () => walk(TRASH_DIR);

export default {
  name,
  dirs,
  ensureStorage,
  checkStorageAccess,
  beginWrite,
  commit,
  abort,
  openRead,
  stat,
  exists,
  moveToTrash,
  remove,
  restoreFromTrash,
  removeFromTrash,
  statTrash,
  sha256Of,
  listDataObjects,
  listTrashObjects,
};
